<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand logo"><img src="images/logo.png"alt="logo"/></div>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/csl">HOME</a></li>
                <li><a href="about.php">ABOUT CSL</a></li>
                <li><a href="staff.php">STAFF</a></li>
                <li><a href="">NEW EQUIPMENTS</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">LABORATORIES
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" style="font-size:small">
                        <li><a href="">Biological laboratory</a></li>
                        <li><a href="">Chemistry laboratory</a></li>
                        <li><a href="">Scanning Electron Microscope laboratory</a></li>
                        <li><a href="">Biotechnology laboratory</a></li>
                        <li><a href="">Nuclear Electric Resonance laboratory</a></li>
                    </ul>
                </li>
                <li><a href="">GALLERY</a></li>
            </ul>
        </div>
    </div>
</nav>